name: Debug Docker Build

on:
  push:
    branches: [ main ]

jobs:
  debug-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (verbose)
        env:
          DOCKER_BUILDKIT: 0
        run: |
          docker build \
            --no-cache \
            --progress=plain \
            -t alicia-ia-debug .
