name: Debug Docker Build

on:
  push:
    # Opcional: limita a la rama donde estás trabajando
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image (verbose)
        env:
          DOCKER_BUILDKIT: 0    # desactiva BuildKit para logs “plain”
        run: |
          docker build \
            --no-cache \
            --progress=plain \
            -t alicia-ia-debug .
