name: QA Pipeline

# Se dispara en push o pull_request sobre cualquier rama
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # o la versión que uses

      - name: Install dependencies
        run: npm ci

      - name: Type-check (TS)
        run: npm run typecheck

      - name: Lint code (ESLint)
        run: npm run lint

      - name: Check formatting (Prettier)
        run: npx prettier --check "src/**/*.{js,ts,css,html,json}"

      - name: Build (Vite)
        run: npm run build
